const Web3=require('web3');
const contractAddress='0x86c7d17e67a4d750d46b02b945e2aa0b1669db7c';
const abi=[{"constant":true,"inputs":[{"name":"","type":"uint256"}],"name":"carToOwner","outputs":[{"name":"","type":"address"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"","type":"address"}],"name":"userCarCount","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_dist","type":"address"},{"name":"_owner","type":"address"},{"name":"_carId","type":"uint256"},{"name":"_user","type":"string"}],"name":"sendFromManToDist","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[{"name":"_id","type":"uint256"}],"name":"getCar","outputs":[{"name":"name","type":"string"},{"name":"number","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"","type":"uint256"}],"name":"idToCar","outputs":[{"name":"name","type":"string"},{"name":"carNumber","type":"string"},{"name":"currentState","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":false,"inputs":[{"name":"_name","type":"string"},{"name":"_carNumberinBytes","type":"bytes32"},{"name":"_user","type":"string"},{"name":"_carNumber","type":"string"}],"name":"addCar","outputs":[{"name":"name","type":"string"},{"name":"carNumber","type":"string"},{"name":"senderAdd","type":"address"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[{"name":"","type":"bytes32"}],"name":"numberToCar","outputs":[{"name":"name","type":"string"},{"name":"carNumber","type":"string"},{"name":"currentState","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"","type":"uint256"}],"name":"cars","outputs":[{"name":"name","type":"string"},{"name":"carNumber","type":"string"},{"name":"currentState","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[{"name":"_owner","type":"address"}],"name":"getCarsByUser","outputs":[{"name":"","type":"uint256[]"}],"payable":false,"stateMutability":"view","type":"function"},{"anonymous":false,"inputs":[{"indexed":false,"name":"_id","type":"uint256"},{"indexed":false,"name":"_name","type":"string"},{"indexed":false,"name":"_carNumber","type":"string"}],"name":"newCar","type":"event"}];
web3 = new Web3(new Web3.providers.HttpProvider("https://rinkeby.infura.io/"));
const SCMContract= new web3.eth.Contract(abi, contractAddress);

module.exports={
    ABI:abi,
    contract:SCMContract,
    address:contractAddress
}